// 直播课件/50、[直播]8月15日Vue .js（五）/20190815Vue.js05/vue-05/源码/app/src/views/Home.vue
<template>
  <div>
    <h2>商品列表</h2>
    <select v-model="sort">
        <option value="desc">从高到低</option>
        <option value="asc">从低到高</option>
    </select>
    <ul class="item-list">
      <li class="head">
        <span>名称</span>
        <span>价格</span>
        <span>操作</span>
      </li>
      <li v-for="item of items" :key="item.id">
        <span>
          <router-link :to="{name: 'item', params: {itemId: item.id}}">{{item.name}}</router-link>
        </span>
        <span>{{item.price|RMB}}</span>
        <span>
          <button>添加到购物车</button>
        </span>
      </li>
    </ul>
  </div>
</template>

<script>
import axios from "axios"
import {RMB} from '@/filters/filters'

export default {
  name: "home",
  data() {
    return {
      items: []
    };
  },
  filters: {
      RMB
  },
  computed: {
      sort: {
          get() {
            //   console.log(this.$route.query);
              return this.$route.query.sort || 'desc';
          },
          set(newVal) {
            //   console.log(newVal);
            this.$router.push({name: 'home', query: {sort: newVal}});
          }
      }
  },
  created() {
    this.getItems();
  },
//   watch: {
//       $route(to, from) {
//           // console.log('$route变了');
//           this.getItems();
//       }
//   },
  methods: {
      getItems() {
        axios({
            url: "/api/items",
            params: {
                sort: this.sort
            }
        }).then(({ data }) => {
            this.items = data;
        });
      }
  },


  beforeRouteEnter(to, from, next) {
      console.log('beforeRouteEnter');
      next(vm => {
          console.log(vm);
      });
  },
  beforeRouteUpdate(to, from, next) {
      console.log('beforeRouteUpdate', this);
      this.getItems();
      next();
  },
  beforeRouteLeave(to, from, next) {
      console.log('beforeRouteLeave', this);
      next();
  }
};
</script>
<style scoped>
ul {
    margin: 0;
    padding: 0;
}

li {
    list-style: none;
}

.item-list li {
    padding: 10px;
    display: flex;
    justify-content: space-between;
    height: 30px;
    line-height: 30px;
    border-bottom: 1px dotted #333;
}
.item-list li.head {
    font-weight: bold;
}
.item-list li span {
    min-width: 200px;
}
</style>

// 直播课件/44、[直播]7月31日react.js（五）/20190731React.js05/react-05/源码/myapp-router/src/BaseApp/view/Home.js
import React from 'react';

import {Link} from 'react-router-dom'

import queryString from 'qs';

import Pagination from '../component/Pagination';

export default class Home extends React.Component {

    constructor(props) {
        super(props);

        // this.state = {
        //     sort: 'desc'
        // }

        this.changeSort = this.changeSort.bind(this);
    }

    changeSort({target: {value: sort}}) {
        let {history: {push}} = this.props;
        // console.log(push);
        push('/?sort=' + sort);
    }

    render(){
        // console.log(this.props);
        // console.log(window.location);
        let {items, location: {search}} = this.props;
        // let {sort} = this.state;
        let page = parseInt(this.props.match.params.page) || 1;
        // console.log(page);

        // console.log(search);
        // let qs = new URLSearchParams(search);
        // let sort = qs.get('sort');
        // console.log(sort1);

        let qsTest = queryString.parse(search, {ignoreQueryPrefix: true});
        // console.log(qsTest);
        let sort = qsTest.sort || 'desc';

        // 根据state中sort值进行排序
        items = items.sort((a, b) => sort === 'asc'  ? a.price - b.price : b.price - a.price);

        return(
            <div>
                <h2>商品列表</h2>
                <select defaultValue={sort} onChange={this.changeSort}>
                    <option value="desc">从高到低</option>
                    <option value="asc">从低到高</option>
                </select>
                <ul className="item-list">
                    <li className="head">
                        <span>名称</span>
                        <span>价格</span>
                    </li>
                    {
                        items.map(item=>(
                            <li key={item.id}>
                                <span>
                                    <Link to={'/item/' + item.id}>  {item.name}
                                    </Link>
                                </span>
                                <span>￥ {(item.price / 100).toFixed(2)}</span>
                            </li>
                        ))
                    }
                </ul>

                <Pagination pages={10} page={page} />
            </div>
        );
    }

}
